apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: weather-app
  namespace: flux-system
spec:
  interval: 1m
  path: "./deployment/base"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-k8s-deployments-book-weather-app
  validation: client
  suspend: false
