apiVersion: apps/v1
kind: Deployment
metadata:
  name: zurich-weather-app
  labels:
    app: zurich-weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zurich-weather-app
  template:
    metadata:
      labels:
        app: zurich-weather-app
    spec:
      containers:
        - name: zurich-weather-app
          image: savagame/gitops-k8s-deployments:202511171409-52df6a82
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
