name: Publish Docker Image
on:
  push:
    branches:
      - "main"
      - "release"
jobs:
  push_to_registry:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v4
      - name: Generate image tag
        id: vars
        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M)-${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Extract metadata (tags, labels) for docker
      #   id: meta
      #   uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      #   with:
      #     images: savagame/gitops-k8s-deployments:${{ env.IMAGE_TAG }}
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./src/dockerfile
          push: true
          tags: savagame/gitops-k8s-deployments:${{ env.IMAGE_TAG }}

      - name: Update deployment.yaml with new image tag
        run: |
          sed -i "s|image: savagame/gitops-k8s-deployments:.*|image: savagame/gitops-k8s-deployments:${{ env.IMAGE_TAG }}|" deployment/deployment.yaml
      - name: Commit updated deployment.yaml
        run: |
          git config user.name "savagame"
          git config user.email "goodhabitsamsam@gmail.com"
          git add deployment/deployment.yaml
          git commit -m "Update deployment image to ${{ env.IMAGE_TAG }}" || echo "No changes to commit"
          git push
